# Analise arquivos raw contas-receber.csv

In [1]:
import os
import pandas as pd
from pandasql import sqldf

pysqldf = lambda q: sqldf(q, globals())

In [2]:
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath('.'))))
DATA_DIR = os.path.join(BASE_DIR, 'data')
RAW_DIR =  os.path.join(DATA_DIR, 'raw')

In [3]:
df = pd.read_csv(os.path.join(RAW_DIR, 'contas_receber.csv'), sep=';')
df.shape

(507, 9)

## Analise exploratória

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 507 entries, 0 to 506
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_titulo_receber  507 non-null    str
 1   id_cliente         497 non-null    str
 2   data_emissao       507 non-null    str
 3   data_vencimento    507 non-null    str
 4   data_recebimento   288 non-null    str
 5   valor_titulo       497 non-null    float64
 6   valor_recebido     497 non-null    float64
 7   status             497 non-null    str
 8   forma_recebimento  497 non-null    str
dtypes: float64(2), str(7)
memory usage: 35.8 KB

In [5]:
df.isna().sum()

id_titulo_receber      0
id_cliente            10
data_emissao           0
data_vencimento        0
data_recebimento     219
valor_titulo          10
valor_recebido        10
status                10
forma_recebimento     10
dtype: int64

In [6]:
df.head()

,id_titulo_receber,id_cliente,data_emissao,data_vencimento,data_recebimento,valor_titulo,valor_recebido,status,forma_recebimento
0,CR000001,C0027,2026-02-26,2026-04-12,2026-04-12,10168.68,10168.68,Pago,PIX
1,CR000002,C0012,2026-04-23,2026-06-22,2026-06-26,9370.77,9370.77,Pago,Boleto
2,CR000003,C0028,2026-04-14,2026-06-13,NaN,914.85,0.00,Em aberto,Transferência
3,CR000004,C0026,2026-06-06,2026-07-21,NaN,8707.44,0.00,Em aberto,PIX
4,CR000005,C0034,2026-01-28,2026-02-25,2026-02-25,7016.44,7016.44,Pago,Cartão

In [7]:
df.tail()

,id_titulo_receber,id_cliente,data_emissao,data_vencimento,data_recebimento,valor_titulo,valor_recebido,status,forma_recebimento
502,CR000415,C0027,2026-04-13,2026-05-28,2026-05-30,10601.62,10601.62,Pago,Transferência
503,CR000033,C0013,2026-01-01,2026-01-08,08-01-2026,652.61,652.61,Pago,Cartão
504,CR000461,C0010,2026-04-06,2026-05-06,2026-05-11,14784.04,14784.04,Pago,Cartão
505,CR000156,C0040,2026-04-03,2026-06-02,NaN,11488.59,0.00,Em aberto,boleto
506,CR000250,C0047,2026-01-26,2026-02-09,NaN,13831.01,0.00,Em aberto,Transferência

In [8]:
df.sample(5)

,id_titulo_receber,id_cliente,data_emissao,data_vencimento,data_recebimento,valor_titulo,valor_recebido,status,forma_recebimento
435,CR000436,C0003,2026-05-14,2026-05-28,2026-05-30,2030.81,2030.81,Pago,Transferência
13,CR000014,C0047,2026-07-22,2026-08-21,2026-08-24,9297.47,9297.47,Pago,Cartão
501,CR000014,C0047,2026-07-22,2026-08-21,2026-08-24,9297.47,9297.47,Pago,Cartão
417,CR000418,C0045,2026-03-30,2026-05-29,NaN,NaN,0.00,Em aberto,Boleto
475,CR000476,C0032,2026-04-03,2026-04-10,NaN,4427.12,0.00,Vencido,Boleto

In [9]:
df.isnull().sum()

id_titulo_receber      0
id_cliente            10
data_emissao           0
data_vencimento        0
data_recebimento     219
valor_titulo          10
valor_recebido        10
status                10
forma_recebimento     10
dtype: int64

In [13]:
q = '''SELECT id_titulo_receber
            , id_cliente
            , data_recebimento
            , valor_titulo
            , valor_recebido
            , status
            , forma_recebimento
        FROM df
        WHERE id_cliente isnull
            or data_recebimento isnull
            or valor_titulo isnull
            or valor_recebido isnull
            or status isnull
            or forma_recebimento isnull

'''
pysqldf(q)

,id_titulo_receber,id_cliente,data_recebimento,valor_titulo,valor_recebido,status,forma_recebimento
0,CR000003,C0028,NaN,914.85,0.00,Em aberto,Transferência
1,CR000004,C0026,NaN,8707.44,0.00,Em aberto,PIX
2,CR000006,C0048,2026-02-10,5994.75,5994.75,Pago,NaN
3,CR000008,C0028,NaN,13809.78,0.00,Em aberto,Boleto
4,CR000009,C0030,NaN,6939.96,0.00,Em aberto,PIX
...,...,...,...,...,...,...,...
248,CR000497,C0038,NaN,3146.13,0.00,Vencido,Boleto
249,CR000498,C0041,NaN,5524.25,0.00,Em aberto,Cartão
250,CR000309,C0017,NaN,1122.10,0.00,Em aberto,Transferência
251,CR000156,C0040,NaN,11488.59,0.00,Em aberto,boleto
252,CR000250,C0047,NaN,13831.01,0.00,Em aberto,Transferência

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 507 entries, 0 to 506
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_titulo_receber  507 non-null    str
 1   id_cliente         497 non-null    str
 2   data_emissao       507 non-null    str
 3   data_vencimento    507 non-null    str
 4   data_recebimento   288 non-null    str
 5   valor_titulo       497 non-null    float64
 6   valor_recebido     497 non-null    float64
 7   status             497 non-null    str
 8   forma_recebimento  497 non-null    str
dtypes: float64(2), str(7)
memory usage: 35.8 KB

## Tratamento de dados

In [15]:
df_original = df.copy()

In [16]:
df = df.fillna('NAO INFORMADO')

In [17]:
# Remove espaços antes/depois dos nomes
df.columns = df.columns.str.strip()

In [18]:
campos_texto = [
    "id_titulo_receber",
    "id_cliente",
    "status",
    "forma_recebimento"
]

In [19]:
for campo in campos_texto:

    df[campo] = (
        df[campo]
        .astype("string")
        .str.strip()
    )

In [20]:
campos_numericos = [
    "valor_titulo",
    "valor_recebido"
]

In [21]:
for campo in campos_numericos:
    df[campo] = (
        df[campo].replace('NAO INFORMADO', 0)
        .astype("float")
    )

In [22]:
# campos datas

df['data_emissao'] = df['data_emissao'].replace('NAO INFORMADO', '1900-01-01', regex=True)
df['data_emissao'] = df['data_emissao'].replace('/', '-',  regex=True)

df['data_vencimento'] = df['data_vencimento'].replace('NAO INFORMADO', '1900-01-01', regex=True)
df['data_vencimento'] = df['data_vencimento'].replace('/', '-',  regex=True)

df['data_recebimento'] = df['data_recebimento'].replace('NAO INFORMADO', '1900-01-01', regex=True)
df['data_recebimento'] = df['data_recebimento'].replace('/', '-',  regex=True)

In [23]:
df['data_emissao'] = pd.to_datetime(df['data_emissao'], format='mixed')

In [24]:
df['data_vencimento'] = pd.to_datetime(df['data_vencimento'], format='mixed')

In [25]:
df['data_recebimento'] = pd.to_datetime(df['data_recebimento'], format='mixed')

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 507 entries, 0 to 506
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_titulo_receber  507 non-null    string
 1   id_cliente         507 non-null    string
 2   data_emissao       507 non-null    datetime64[us]
 3   data_vencimento    507 non-null    datetime64[us]
 4   data_recebimento   507 non-null    datetime64[us]
 5   valor_titulo       507 non-null    float64
 6   valor_recebido     507 non-null    float64
 7   status             507 non-null    string
 8   forma_recebimento  507 non-null    string
dtypes: datetime64[us](3), float64(2), string(4)
memory usage: 35.8 KB

In [27]:
df.head()

,id_titulo_receber,id_cliente,data_emissao,data_vencimento,data_recebimento,valor_titulo,valor_recebido,status,forma_recebimento
0,CR000001,C0027,2026-02-26,2026-04-12,2026-04-12,10168.68,10168.68,Pago,PIX
1,CR000002,C0012,2026-04-23,2026-06-22,2026-06-26,9370.77,9370.77,Pago,Boleto
2,CR000003,C0028,2026-04-14,2026-06-13,1900-01-01,914.85,0.00,Em aberto,Transferência
3,CR000004,C0026,2026-06-06,2026-07-21,1900-01-01,8707.44,0.00,Em aberto,PIX
4,CR000005,C0034,2026-01-28,2026-02-25,2026-02-25,7016.44,7016.44,Pago,Cartão

In [28]:
df.tail()

,id_titulo_receber,id_cliente,data_emissao,data_vencimento,data_recebimento,valor_titulo,valor_recebido,status,forma_recebimento
502,CR000415,C0027,2026-04-13,2026-05-28,2026-05-30,10601.62,10601.62,Pago,Transferência
503,CR000033,C0013,2026-01-01,2026-01-08,2026-08-01,652.61,652.61,Pago,Cartão
504,CR000461,C0010,2026-04-06,2026-05-06,2026-05-11,14784.04,14784.04,Pago,Cartão
505,CR000156,C0040,2026-04-03,2026-06-02,1900-01-01,11488.59,0.00,Em aberto,boleto
506,CR000250,C0047,2026-01-26,2026-02-09,1900-01-01,13831.01,0.00,Em aberto,Transferência

In [29]:
df.sample(5)

,id_titulo_receber,id_cliente,data_emissao,data_vencimento,data_recebimento,valor_titulo,valor_recebido,status,forma_recebimento
10,CR000011,C0026,2026-04-16,2026-05-07,2026-05-11,6928.02,6928.02,Pago,Boleto
59,CR000060,C0046,2026-06-02,2026-07-02,1900-01-01,9553.22,0.00,Em aberto,Transferência
404,CR000405,C0047,2026-08-11,2026-08-18,2026-08-20,2568.15,2568.15,Pago,Boleto
195,CR000196,C0005,2026-01-06,2026-03-07,1900-01-01,12089.24,0.00,Em aberto,Transferência
326,CR000327,C0006,2026-04-29,2026-05-13,2026-05-10,4148.21,4148.21,Pago,Cartão