# Analise arquivos raw vendas.csv

In [1]:
import os
import pandas as pd
from pandasql import sqldf

pysqldf = lambda q: sqldf(q, globals())

In [2]:
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath('.'))))
DATA_DIR = os.path.join(BASE_DIR, 'data')
RAW_DIR =  os.path.join(DATA_DIR, 'raw')

In [3]:
df = pd.read_csv(os.path.join(RAW_DIR, 'vendas.csv'), sep=';')
df.shape

(710, 10)

## Analise exploratória

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 710 entries, 0 to 709
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venda         710 non-null    str
 1   data_venda       710 non-null    str
 2   id_cliente       695 non-null    str
 3   id_produto       695 non-null    str
 4   quantidade       696 non-null    float64
 5   valor_unitario   696 non-null    float64
 6   desconto         695 non-null    float64
 7   forma_pagamento  696 non-null    str
 8   status_venda     696 non-null    str
 9   valor_total      695 non-null    float64
dtypes: float64(4), str(6)
memory usage: 55.6 KB

In [5]:
df.isna().sum()

id_venda            0
data_venda          0
id_cliente         15
id_produto         15
quantidade         14
valor_unitario     14
desconto           15
forma_pagamento    14
status_venda       14
valor_total        15
dtype: int64

In [6]:
df.head()

,id_venda,data_venda,id_cliente,id_produto,quantidade,valor_unitario,desconto,forma_pagamento,status_venda,valor_total
0,V000001,2026-06-21,NaN,P0045,14.0,156.91,0.0,Boleto,Faturada,2196.74
1,V000002,2026-04-13,C0027,P0064,10.0,15.17,50.0,PIX,faturada,101.70
2,V000003,2026-07-17,C0006,P0041,9.0,215.90,5.0,PIX,Cancelada,1938.10
3,V000004,2026-04-03,C0030,P0053,2.0,133.92,10.0,Transferência,Faturada,257.84
4,V000005,2026-02-03,C0049,P0007,7.0,91.86,0.0,Transferência,NaN,643.02

In [7]:
df.tail()

,id_venda,data_venda,id_cliente,id_produto,quantidade,valor_unitario,desconto,forma_pagamento,status_venda,valor_total
705,V000058,2026-06-25,C0043,P0033,12.0,110.86,5.0,PIX,Faturada,1325.32
706,V000236,2026-06-08,C0007,P0068,5.0,68.78,10.0,Cartão,Faturada,333.90
707,V000384,2026-05-20,C0027,P0064,29.0,14.52,5.0,PIX,Faturada,416.08
708,V000286,2026-03-22,NaN,P0063,10.0,128.07,50.0,Transferência,Devolvida,1230.70
709,V000554,2026-07-31,C0031,NaN,29.0,114.06,0.0,Transferência,Cancelada,3307.74

In [8]:
df.sample(5)

,id_venda,data_venda,id_cliente,id_produto,quantidade,valor_unitario,desconto,forma_pagamento,status_venda,valor_total
546,V000547,2026-06-19,C0037,P0003,29.0,NaN,50.0,Cartão,Faturada,2339.02
354,V000355,2026-02-01,C0030,P0014,26.0,104.61,0.0,PIX,Faturada,2719.86
570,V000571,2026-02-10,C0024,P0031,21.0,195.71,0.0,Cartão,Faturada,4109.91
245,V000246,2026-03-01,C0048,P0045,2.0,151.07,50.0,PIX,Faturada,252.14
316,V000317,2026-05-31,C0006,P0013,5.0,163.12,20.0,Transferência,Faturada,795.60

In [9]:
df.isnull().sum()

id_venda            0
data_venda          0
id_cliente         15
id_produto         15
quantidade         14
valor_unitario     14
desconto           15
forma_pagamento    14
status_venda       14
valor_total        15
dtype: int64

In [10]:
q = '''SELECT id_venda
            , id_cliente
            , id_produto
            , quantidade
            , valor_unitario
            , desconto
            , forma_pagamento
            , status_venda
            , valor_total
        FROM df
        WHERE id_cliente isnull
            or id_produto isnull
            or quantidade isnull
            or valor_unitario isnull
            or desconto isnull
            or forma_pagamento isnull
            or status_venda isnull
            or status_venda isnull
            or valor_total 

'''
pysqldf(q)

,id_venda,id_cliente,id_produto,quantidade,valor_unitario,desconto,forma_pagamento,status_venda,valor_total
0,V000001,NaN,P0045,14.0,156.91,0.0,Boleto,Faturada,2196.74
1,V000002,C0027,P0064,10.0,15.17,50.0,PIX,faturada,101.70
2,V000003,C0006,P0041,9.0,215.90,5.0,PIX,Cancelada,1938.10
3,V000004,C0030,P0053,2.0,133.92,10.0,Transferência,Faturada,257.84
4,V000005,C0049,P0007,7.0,91.86,0.0,Transferência,NaN,643.02
...,...,...,...,...,...,...,...,...,...
691,V000058,C0043,P0033,12.0,110.86,5.0,PIX,Faturada,1325.32
692,V000236,C0007,P0068,5.0,68.78,10.0,Cartão,Faturada,333.90
693,V000384,C0027,P0064,29.0,14.52,5.0,PIX,Faturada,416.08
694,V000286,NaN,P0063,10.0,128.07,50.0,Transferência,Devolvida,1230.70
695,V000554,C0031,NaN,29.0,114.06,0.0,Transferência,Cancelada,3307.74

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 710 entries, 0 to 709
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venda         710 non-null    str
 1   data_venda       710 non-null    str
 2   id_cliente       695 non-null    str
 3   id_produto       695 non-null    str
 4   quantidade       696 non-null    float64
 5   valor_unitario   696 non-null    float64
 6   desconto         695 non-null    float64
 7   forma_pagamento  696 non-null    str
 8   status_venda     696 non-null    str
 9   valor_total      695 non-null    float64
dtypes: float64(4), str(6)
memory usage: 55.6 KB

## Tratamento de dados

In [12]:
df_original = df.copy()

In [13]:
df = df.fillna('NAO INFORMADO')

In [14]:
# Remove espaços antes/depois dos nomes
df.columns = df.columns.str.strip()

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 710 entries, 0 to 709
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venda         710 non-null    str
 1   data_venda       710 non-null    str
 2   id_cliente       710 non-null    str
 3   id_produto       710 non-null    str
 4   quantidade       710 non-null    object
 5   valor_unitario   710 non-null    object
 6   desconto         710 non-null    object
 7   forma_pagamento  710 non-null    str
 8   status_venda     710 non-null    str
 9   valor_total      710 non-null    object
dtypes: object(4), str(6)
memory usage: 55.6+ KB

In [16]:
campos_texto = [
    "id_venda",
    "id_cliente",
    "id_produto",
    "forma_pagamento",
    "forma_pagamento",
    "status_venda"
]

In [17]:
for campo in campos_texto:

    df[campo] = (
        df[campo]
        .astype("string")
        .str.strip()
    )

In [18]:
campos_numericos = [
    "quantidade",
    "valor_unitario",
    "desconto",
    "valor_total"
]

In [19]:
for campo in campos_numericos:
    df[campo] = (
        df[campo].replace('NAO INFORMADO', 0)
        .astype("float")
    )

In [20]:
# campos datas

df['data_venda'] = df['data_venda'].replace('NAO INFORMADO', '1900-01-01', regex=True)
df['data_venda'] = df['data_venda'].replace('/', '-',  regex=True)

In [21]:
df['data_venda'] = pd.to_datetime(df['data_venda'], format='mixed')

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 710 entries, 0 to 709
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venda         710 non-null    string
 1   data_venda       710 non-null    datetime64[us]
 2   id_cliente       710 non-null    string
 3   id_produto       710 non-null    string
 4   quantidade       710 non-null    float64
 5   valor_unitario   710 non-null    float64
 6   desconto         710 non-null    float64
 7   forma_pagamento  710 non-null    string
 8   status_venda     710 non-null    string
 9   valor_total      710 non-null    float64
dtypes: datetime64[us](1), float64(4), string(5)
memory usage: 55.6 KB

In [23]:
df.head()

,id_venda,data_venda,id_cliente,id_produto,quantidade,valor_unitario,desconto,forma_pagamento,status_venda,valor_total
0,V000001,2026-06-21,NAO INFORMADO,P0045,14.0,156.91,0.0,Boleto,Faturada,2196.74
1,V000002,2026-04-13,C0027,P0064,10.0,15.17,50.0,PIX,faturada,101.70
2,V000003,2026-07-17,C0006,P0041,9.0,215.90,5.0,PIX,Cancelada,1938.10
3,V000004,2026-04-03,C0030,P0053,2.0,133.92,10.0,Transferência,Faturada,257.84
4,V000005,2026-02-03,C0049,P0007,7.0,91.86,0.0,Transferência,NAO INFORMADO,643.02

In [24]:
df.tail()

,id_venda,data_venda,id_cliente,id_produto,quantidade,valor_unitario,desconto,forma_pagamento,status_venda,valor_total
705,V000058,2026-06-25,C0043,P0033,12.0,110.86,5.0,PIX,Faturada,1325.32
706,V000236,2026-06-08,C0007,P0068,5.0,68.78,10.0,Cartão,Faturada,333.90
707,V000384,2026-05-20,C0027,P0064,29.0,14.52,5.0,PIX,Faturada,416.08
708,V000286,2026-03-22,NAO INFORMADO,P0063,10.0,128.07,50.0,Transferência,Devolvida,1230.70
709,V000554,2026-07-31,C0031,NAO INFORMADO,29.0,114.06,0.0,Transferência,Cancelada,3307.74

In [25]:
df.sample(5)

,id_venda,data_venda,id_cliente,id_produto,quantidade,valor_unitario,desconto,forma_pagamento,status_venda,valor_total
410,V000411,2026-02-18,C0047,P0054,20.0,23.22,5.0,Boleto,Faturada,459.40
117,V000118,2026-07-03,C0041,P0024,26.0,31.84,50.0,Transferência,Faturada,777.84
127,V000128,2026-01-09,C0010,P0078,22.0,234.94,0.0,PIX,Faturada,5168.68
70,V000071,2026-06-01,C0028,P0015,10.0,3.11,5.0,Cartão,Faturada,26.10
670,V000671,2026-06-28,C0006,P0052,17.0,44.49,0.0,Boleto,Faturada,756.33