# Analise arquivo raw clientes.csv

In [20]:
import os
import pandas as pd
from pandasql import sqldf

pysqldf = lambda q: sqldf(q, globals())

In [21]:
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath('.')))))
DATA_DIR = os.path.join(BASE_DIR, 'data')
RAW_DIR =  os.path.join(DATA_DIR, 'raw')

In [22]:
df = pd.read_csv(os.path.join(RAW_DIR, 'clientes.csv'), sep=';')
df.shape

(51, 7)

## Analise exploratória

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_cliente      51 non-null     str
 1   nome_cliente    50 non-null     str
 2   cidade          50 non-null     str
 3   uf              50 non-null     str
 4   segmento        50 non-null     str
 5   limite_credito  49 non-null     str
 6   status          50 non-null     str
dtypes: str(7)
memory usage: 2.9 KB

In [24]:
df.isna().sum()

id_cliente        0
nome_cliente      1
cidade            1
uf                1
segmento          1
limite_credito    2
status            1
dtype: int64

In [25]:
df.head()

,id_cliente,nome_cliente,cidade,uf,segmento,limite_credito,status
0,C0001,Comercial Presidente 01,Regente Feijó,SP,Varejo,60616.29,Ativo
1,C0002,Mercado Central 02,NaN,SP,Varejo,55752.46,Ativo
2,C0003,Supermercado Avenida 03,Santo Anastácio,SP,Varejo,7234.79,Ativo
3,C0004,Mercado Central 04,Presidente Prudente,SP,Mercado,58701.47,Ativo
4,C0005,Supermercado União 05,pirapozinho,SP,Food Service,49194.93,Ativo

In [26]:
df.tail()

,id_cliente,nome_cliente,cidade,uf,segmento,limite_credito,status
46,C0047,Supermercado Avenida 47,Presidente Prudente,SP,Varejo,77674.72,Ativo
47,C0048,Comercial Oeste 48,Santo Anastácio,SP,Food Service,41101.88,Ativo
48,C0049,Mercado Esperança 49,Presidente Prudente,SP,Mercado,33422.98,Ativo
49,C0050,Empório Prudente 50,Rancharia,NaN,Atacado,36725.56,Ativo
50,C0014,Mercado Ideal 14,Regente Feijó,SP,Mercado,NaN,Ativo

In [27]:
df.sample(5)

,id_cliente,nome_cliente,cidade,uf,segmento,limite_credito,status
41,C0042,Supermercado União 42,Santo Anastácio,SP,Food Service,69787.76,Ativo
20,C0021,Rede Bom Preço 21,Pirapozinho,SP,Mercado,43214.47,Ativo
7,C0008,Rede Bom Preço 08,Presidente Bernardes,SP,Atacado,65534.62,Ativo
27,C0028,Distribuidora Nova Era 28,Pirapozinho,SP,Mercado,33043.54,Ativo
47,C0048,Comercial Oeste 48,Santo Anastácio,SP,Food Service,41101.88,Ativo

In [28]:
df.isnull().sum()

id_cliente        0
nome_cliente      1
cidade            1
uf                1
segmento          1
limite_credito    2
status            1
dtype: int64

In [29]:
q = '''SELECT id_cliente
                , nome_cliente
                , cidade
                , uf
                , segmento
                , status
            FROM df
        WHERE nome_cliente isnull
                or cidade isnull
                or uf isnull
                or segmento isnull
                or status isnull
    '''
print(pysqldf(q))

  id_cliente         nome_cliente                cidade   uf segmento status
0      C0002   Mercado Central 02                   NaN   SP   Varejo  Ativo
1      C0030                  NaN  Presidente Bernardes   SP  Atacado  Ativo
2      C0036    Rede Bom Preço 36   Presidente Prudente   SP      NaN    NaN
3      C0050  Empório Prudente 50             Rancharia  NaN  Atacado  Ativo

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_cliente      51 non-null     str
 1   nome_cliente    50 non-null     str
 2   cidade          50 non-null     str
 3   uf              50 non-null     str
 4   segmento        50 non-null     str
 5   limite_credito  49 non-null     str
 6   status          50 non-null     str
dtypes: str(7)
memory usage: 2.9 KB

## Tratamento de dados

In [31]:
df_original = df.copy()

In [32]:
df = df.fillna('NAO INFORMADO')

In [33]:
df[['limite_credito']] = df[['limite_credito']].replace('NAO INFORMADO', 0)

In [34]:
df['limite_credito'] = pd.to_numeric(df['limite_credito'], errors='coerce')

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_cliente      51 non-null     str
 1   nome_cliente    51 non-null     str
 2   cidade          51 non-null     str
 3   uf              51 non-null     str
 4   segmento        51 non-null     str
 5   limite_credito  50 non-null     float64
 6   status          51 non-null     str
dtypes: float64(1), str(6)
memory usage: 2.9 KB

In [36]:
df.sample(10)

,id_cliente,nome_cliente,cidade,uf,segmento,limite_credito,status
40,C0041,Mercado Central 41,Regente Feijó,SP,Varejo,54423.71,Ativo
14,C0015,Comercial Oeste 15,Rancharia,SP,Food Service,25246.09,Ativo
16,C0017,Supermercado Real 17,Presidente Bernardes,SP,Food Service,25080.57,Ativo
29,C0030,NAO INFORMADO,Presidente Bernardes,SP,Atacado,22958.92,Ativo
45,C0046,Mercado Central 46,Regente Feijó,SP,Food Service,65601.67,Ativo
28,C0029,Mercado São Lucas 29,Presidente Prudente,SP,Atacado,41645.43,Ativo
23,C0024,Casa das Compras 24,Martinópolis,SP,Varejo,56021.26,Ativo
50,C0014,Mercado Ideal 14,Regente Feijó,SP,Mercado,0.00,Ativo
27,C0028,Distribuidora Nova Era 28,Pirapozinho,SP,Mercado,33043.54,Ativo
15,C0016,Mercado Central 16,Presidente Bernardes,SP,Varejo,22178.61,Ativo

## Salvando dados de clientes em Bronze

In [37]:
BRONZE_DIR = os.path.join(DATA_DIR, 'bronze')

In [38]:
df.to_csv(os.path.join(BRONZE_DIR, 'b_clientes.csv'), index=False)